import * as fs from 'fs';
import * as path from 'path';

export class Logger {
    private outputDir: string;
    private logFile: string;
    private sqlFiles: string[] = [];
    private startTime: number;

    constructor(outputDir: string = './supabase-migrator') {
        this.outputDir = outputDir;
        this.startTime = Date.now();
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        this.logFile = path.join(outputDir, `migration-${timestamp}.log`);
        this.ensureOutputDir();
    }

    private ensureOutputDir(): void {
        if (!fs.existsSync(this.outputDir)) {
            fs.mkdirSync(this.outputDir, { recursive: true });
        }
    }

    private writeToFile(message: string): void {
        fs.appendFileSync(this.logFile, message + '\n');
    }

    log(message: string, level: 'info' | 'warn' | 'error' | 'success' = 'info'): void {
        const timestamp = new Date().toISOString();
        const logMessage = `[${timestamp}] [${level.toUpperCase()}] ${message}`;

        console.log(message);
        this.writeToFile(logMessage);
    }

    info(message: string): void {
        this.log(`ℹ ${message}`, 'info');
    }

    success(message: string): void {
        this.log(`✅ ${message}`, 'success');
    }

    warn(message: string): void {
        this.log(`⚠️  ${message}`, 'warn');
    }

    error(message: string): void {
        this.log(`❌ ${message}`, 'error');
    }

    dryRun(message: string): void {
        this.log(`[DRY RUN] ${message}`, 'info');
    }

    writeSqlFile(filename: string, content: string): string {
        const filepath = path.join(this.outputDir, filename);
        const header = `-- Generated by supabase-migrator\n-- Date: ${new Date().toISOString()}\n-- File: ${filename}\n\n`;
        fs.writeFileSync(filepath, header + content);
        this.sqlFiles.push(filepath);
        this.info(`SQL file written: ${filepath}`);
        return filepath;
    }

    getSqlFiles(): string[] {
        return this.sqlFiles;
    }

    getLogFile(): string {
        return this.logFile;
    }

    getDuration(): number {
        return Date.now() - this.startTime;
    }

    summary(result: { success: boolean; message: string; details?: any }): void {
        const duration = (this.getDuration() / 1000).toFixed(2);

        console.log('\n' + '='.repeat(60));
        if (result.success) {
            this.success(`${result.message}`);
        } else {
            this.error(`${result.message}`);
        }

        if (result.details) {
            if (result.details.itemsProcessed !== undefined) {
                this.info(`Items processed: ${result.details.itemsProcessed}`);
            }
            if (result.details.rowsMigrated !== undefined) {
                this.info(`Rows migrated: ${result.details.rowsMigrated}`);
            }
            if (result.details.errors && result.details.errors.length > 0) {
                this.warn(`Errors: ${result.details.errors.length}`);
            }
            if (result.details.sqlFiles && result.details.sqlFiles.length > 0) {
                this.info(`SQL files generated: ${result.details.sqlFiles.length}`);
            }
        }

        this.info(`Duration: ${duration}s`);
        this.info(`Log file: ${this.logFile}`);
        console.log('='.repeat(60) + '\n');
    }
}
